#!/usr/bin/env python3

import subprocess

import btrfsutil

if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser(
        description="List BTRFS subvolume usage info using QGroups"
    )
    parser.add_argument(
        "path",
        default='/'
    )
    args = parser.parse_args()

    try:
        res = subprocess.check_output(
            f'btrfs qgroup show {args.path}'.split()
        )
    except subprocess.SubprocessError as e:
        print(e)
        exit(1)

    res = [line.split() for line in res.decode().splitlines()[2:]]
    qgroups = {int(line[0].split('/')[1]): line[1:] for line in res}
    subvols = dict(e for e in
                   btrfsutil.SubvolumeIterator(args.path, info=True))

    subvol_usage = [(subvol_path, *qgroups[subvol_info.id])
                    for subvol_path, subvol_info in subvols.items()]

    max_len = max(map(len, subvols.keys()))
    format_str = '{:%i} {}\t{}' % max_len
    print(format_str.format('Path', 'Shared', 'Exclusive'))
    print(format_str.format('----', '------', '---------'))
    for su in subvol_usage:
        print(format_str.format(*su))
