#!/usr/bin/env python3

# TODO: handle slots explicitly?

import os
import re
from portage import db as port_db, root as port_root, dep_getkey, getmaskingstatus
from portage.versions import cpv_getkey, cpv_getversion

portdbapi = port_db[port_root]['porttree'].dbapi
vardbapi  = port_db[port_root]['vartree'].dbapi

def get_pkgs_from_package_ak(fname="/etc/portage/package.accept_keywords"):
    "read the raw lines from the package.accept_keywords file(s)"

    if os.path.isfile(fname):
        with open(fname) as pk:
            lines = pk.readlines()
    elif os.path.isdir(fname):
        lines = []
        for root, dirs, files in os.walk(fname):
            files = [os.path.join(root, f) for f in files if not f.endswith('~')]
            for f in files:
                with open(f) as fp:
                    lines += fp.readlines()

    # find all uncommented, non-empty lines and extract the unique
    # cat/pkg-names; remove any repository specification
    pk_reg = re.compile("^\s*(?!#)\s*(.*)")
    atoms  = [m.partition(':')[0] for l in lines for m in pk_reg.findall(l) if m]
    atoms  = sorted(set(dep_getkey(a) for a in atoms))

    return atoms

def get_upgrade_paths(packages, skiplive=True, skipmasked=True):
    "Find available upgrade paths."

    # get a list of all installed packages; NOTE: add the cat/pkg string to *very*
    # noticeably reduce overhead in the below for-loop
    installed_pkgs = [(p,cpv_getkey(p)) for p in vardbapi.cpv_all()]

    upgrades = []
    for p in packages:
        available = portdbapi.cp_list(p)
        installed = [ip_v for ip_v,ip in installed_pkgs if p == ip]
        av_ver    = [cpv_getversion(m) for m in available]
        ins_ver   = [cpv_getversion(m) for m in installed]

        if ins_ver:
            # find the first installed version in the tree
            idx = -1
            for i,v in enumerate(ins_ver):
                try:
                    idx = av_ver.index(v)
                    break
                except ValueError:
                    # prefix unavailable versions with a '*'
                    ins_ver[i] = "*" + ins_ver[i]

            # list all versions higher than the oldest installed version
            cur_ver = [v for v in av_ver[idx+1:] if ins_ver[0] != v]
            
            if skiplive:
                # skip live upgrades
                cur_ver = [cv for cv in cur_ver if '9999' not in cv]

            if skipmasked:
                cur_available = [e for e in available
                                 if cpv_getversion(e) in cur_ver]

                # only filter versions that are in package.mask
                cur_ver = [cv for cv,ca in zip(cur_ver,cur_available)
                           if "package.mask" not in getmaskingstatus(ca)]

            if cur_ver:
                upgrades.append((p, ', '.join(ins_ver), ', '.join(cur_ver)))
        else:
            upgrades.append((p, '(none)', ', '.join(av_ver)))

    return upgrades

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Find upgrades for unmasked packages."
    )

    parser.add_argument(
        "--no-skip-live",
        dest="skiplive",
        action="store_false",
        help="Do not skip live updates in the output."
    )

    parser.add_argument(
        "--no-skip-masked",
        dest="skipmasked",
        action="store_false",
        help="Do not skip masked versions in the output."
    )

    args = parser.parse_args()

    upgrades = get_upgrade_paths(packages   = get_pkgs_from_package_ak(),
                                 skiplive   = args.skiplive,
                                 skipmasked = args.skipmasked)

    if not upgrades:
        exit("No upgrade paths!")

    # generate a format string for printing
    max_len = tuple(len(max(l, key=len)) for l in zip(*upgrades))
    form_spec = "{0:>%i}: {1:>%i} -> {2:<%i}" % max_len

    # print the upgrade paths
    header = form_spec.format("Name", "Installed", "Available")
    print(header, "-"*len(header), sep="\n")
    for p in upgrades:
        print(form_spec.format(*p))
