#!/bin/sh

make_j="1"

while getopts j: a
do
    case $a in
	j) make_j="$OPTARG";;
    esac
done

if [ "${PWD%%-*}" != "/usr/src/linux" ]
then
    echo "Not in a linux src directory: ${PWD}!\n"
    exit 1
fi

v=$(grep "VERSION =" Makefile | head -n1 | cut -d\  -f3)
p=$(grep "PATCHLEVEL =" Makefile | head -n1 | cut -d\  -f3)
s=$(grep "SUBLEVEL =" Makefile | head -n1 | cut -d\  -f3)
e=$(grep "EXTRAVERSION =" Makefile | head -n1 | cut -d\  -f3)
cur_ver=$v.$p.$s$e
kern_path="/boot/kernel-$cur_ver"
kern_count=$(ls -1 $kern_path* 2>/dev/null| wc -l)
if [ $kern_count -gt 0 ]; then
    kern_path="$kern_path-c$kern_count"
fi

echo "Making linux-$cur_ver"
make -j$make_j &&
    make -j$make_j modules_install &&
    cp arch/x86_64/boot/bzImage $kern_path &&
    cp System.map /boot/System.map-$cur_ver &&
    cp .config /etc/kernels/kernel-config-$cur_ver &&
    grub2-mkconfig -o /boot/grub/grub.cfg
