#!/bin/sh

# A simple script that sets up iptables *correctly*.
iptables -F

# Setup default policies to handle unmatched traffic
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP

wan=wan0
lan_ip=192.168.178.0/24

# Then we lock our services so they only work from the LAN
iptables -I INPUT 1 -i lo -j ACCEPT
iptables -A INPUT -p UDP --dport bootps -i ${wan} -j REJECT
iptables -A INPUT -p UDP --dport domain -i ${wan} -j REJECT

# Allow access to my Samba server (which is restricted to a small set of users)
iptables -A INPUT -p UDP --dport netbios-ns -i ${wan} -s ${lan_ip} -j ACCEPT
iptables -A INPUT -p TCP --dport netbios-ssn -i ${wan} -s ${lan_ip} -j ACCEPT
iptables -A INPUT -p TCP --dport microsoft-ds -i ${wan} -s ${lan_ip} -j ACCEPT

# Allow NTP clients to work
iptables -A INPUT -p UDP --dport ntp -j ACCEPT
iptables -A OUTPUT -p UDP --sport ntp -j ACCEPT

# Allow access to my SSH server (which only allows public key authentication)
iptables -A INPUT -p TCP --dport ssh -i ${wan} -s ${lan_ip} -j ACCEPT

# Drop TCP / UDP packets to privileged ports
iptables -A INPUT -p TCP -i ${wan} -d 0/0 --dport 0:1023 -j DROP
iptables -A INPUT -p UDP -i ${wan} -d 0/0 --dport 0:1023 -j DROP
