#!/bin/sh
#
# Changelog:
#   06.01.2008 - finally fixed this so it finds all modules
#   25.03.2012 - convert to POSIX shell

lsmod | tail -n+2 | cut -d' ' -f1 | while read m;
do
    modinfo -F filename $m
done | xargs du -hsc | sort -h $@
