#!/bin/sh

if [ -z "$1" ]; then
    echo "No block device specified" >&2
    exit
fi

block_path="/sys/block/$1"
if [ ! -d "$block_path" ]; then
    echo "Invalid block device \"$1\"" >&2
    exit
fi

scsi_host=$(readlink -f "$block_path" | sed -e 's:\(.*/host[0-9]\+\)/.*:\1:g')

echo 1 > "$block_path"/device/delete
echo "- - -" > "$scsi_host"/scan
